### ISSUE TITLE
Publish to MELPA

### ISSUE THREAD

**Issue by swflint** [haji-ali/lp-transient#16]
It would be useful to publish this project and its several packages to MELPA for discoverability.

**Comment by swflint** [comment]
All things considered, I'm willing to do the work to do so, but I'll need a PR to point at.

If you'd like to publish to MELPA, it may be wise to update version numbers as well.

**Comment by swflint** [comment]
I've submitted recipes in https://github.com/melpa/melpa/pull/8425.

**Comment by swflint** [comment]
Package recipes submitted in https://github.com/melpa/melpa/pull/8426

**Comment by haji-ali** [comment]
@swflint, I've removed the dependency on `async-completing-read`. The configuration can be done with an advice instead.
I also added a GPL licence.
